# Generated by Django 4.0.2 on 2022-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='fastcampus_fcuser',
        ),
    ]
