# Generated by Django 4.0.2 on 2022-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_alter_fcuser_username_alter_fcuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default=1222, max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
